### PR TITLE
Solutions comparison operators

### PR DESCRIPTION
**Pull request by laradicp**
Add `Base.in(::Tuple{De,Va}, ::Solution{Mo,De,Va})` to allow `==` and `isequal` comparisons between solutions.

### CODE REVIEW

**Comment by guimarqu** [comment]
Ok with the changes but what's the problem of defining `==` for `Solution`?

**Comment by laradicp** [comment]
> Ok with the changes but what's the problem of defining `==` for `Solution`?

No problem. `Base.==` is not imported to Coluna yet, and I would implement like this
```julia
Base.==(s1::Solution, s2::Solution) = isequal(s1, s2)
```
So I didn't know if adding this extra method would be really preferable or if just `isequal` is as easily understandable.

**Comment by guimarqu** [comment]
Documentation says that default implementation of `isequal` calls `==`.

These methods seems to have different behaviors when arguments are `Float64`.
In very special cases, we may have `isequal(sol1,sol2) !== (sol1 == sol2)`.

**Comment by laradicp** [comment]
The problem was actually that `Base.in` is only defined for `Pair`. Since a `Tuple` is used for the `AbstractDict` in Coluna, it threw an error. I took the code from Base and adapted it to `Tuple`. Now both `==` and `isequal` work as expected.

**Review by guimarqu — APPROVED** [review]

**Pull request merged**
