### PR TITLE
Warm start for sub-solvers

### PR DESCRIPTION
**Pull request by guimarqu**

### CODE REVIEW

**Comment by guimarqu** [comment]
@rrsadykov maybe I should rename the method `setprimalwarmstart!`

**Comment by rrsadykov** [comment]
setbasis is good name for me. We also need getbasis.
Why do you use primal solution to set the basis? How does it work? 
In BaPCod Cplex interface, the basis contains variables and also constraints.  Do you think using MOI.VariablePrimalStart() is enough?

I will test getting/setting basis soon, I am now working on storing/restoring storages. I will make a draft pull request soon.

**Comment by guimarqu** [comment]
Sorry I mixed two things. I will do a new PR for the basis. Here you give a primal solution to do a warm start.

**Comment by rrsadykov** [comment]
What is the purpose of this warm start?

**Comment by guimarqu** [comment]
> What is the purpose of this warm start?

Useless at the moment, so it stays here as a draft PR.
It may be more usefull for the IP solver

**Comment by rrsadykov** [comment]
I think then it is better to move this to SolveIpForm. Actually the most useful for IP formulation  is to set the upper bound. I do not know whether IP solvers can make use of the primal solution. In principle, it may be useful only for heuristics embedded in IP solvers. 

For LP formulation, setting primal solution is not useful, we should set basis instead. Moreover, basis should not be set inside the algorithm, but in the node setup. I will implement this, I just need getbasis and setbasis function in the MathProg submodule.

**Comment by rrsadykov** [comment]
I also think we should rename SolveIpForm to SolveMIPForm to make it visually more different from SolveLpForm.

**Comment by guimarqu** [comment]
Stale

**Pull request closed without merging**
