### PR TITLE
Retrieve multiple solutions from `SolveIpForm`

### PR DESCRIPTION
**Pull request by guimarqu**
@artalvpes  This is the fix to generate multiple column each time the pricing callback is run.

Changes : 
- A new parameter in `SolveIpForm` to define the maximum number of solution returned
- Fix the way we retrieve solutions in SolveIpForm
- Change for `(update|add)_(ip|lp)_(primal|dual)_sol` : now we create a new entry in the list of solutions, sort the list, and then the less good solutions are deleted to respect the size of the list (method `bestbound!`). Before this PR, the new solution was replacing a solution of the list even if the replaced solution was better than the new one. (@rrsadykov I think it may allow us to remove `update_all_ip_primal_solutions!` cf #397).
- `set_(lp|ip)_(primal|dual)_sol` -> `unshift_(lp|ip)_(primal|dual)_sol` because I think `set` is misleading when the list has a size > 1. The new method pushes the new solution at the beginning of the list. The new solution is therefore considered as the best solution.

(@ItamarRocha, lot of things related to solutions in this PR)

### CODE REVIEW

**Comment by rrsadykov** [comment]
I agree that the `set_sol` is misleading, but the word `unshift` does not exist and thus even more misleading, i think

**Comment by guimarqu** [comment]
> I agree that the `set_sol` is misleading, but the word `unshift` does not exist and thus even more misleading, i think

I think I should replace by `pushfirst` because it's the name of the method in julia. A lot of languages has a method `unshift` to push something at the beginning of an array.

**Comment by rrsadykov** [comment]
We may leave `set_sol`, but when this function is used, all previous solutions are removed. `set_sol` would be used for the case when the can be only one solution. For example, in column generation, there is only one dual and one primal solution.

**Comment by guimarqu** [comment]
> We may leave `set_sol`, but when this function is used, all previous solutions are removed. `set_sol` would be used for the case when there can be only one solution. For example, in column generation, there is only one dual and one primal solution.

That was my 2nd option, so it's good for me.

**Comment by rrsadykov** [comment]
I think there are two distinct use cases: one we have one solution (`set_sol` is ok for this case). Other case is when we have a list of solutions sorted by bound.  In the latter case, just `add_sol` would be enough i think. Are there any other use cases?

**Comment by guimarqu** [comment]
I also see these two cases. We provide `add_sol` and `update_sol`. The second one adds the solution to the list only if the solution improves the bound.

**Review by rrsadykov — APPROVED** [review]

**Pull request merged**
